Repository sourcegraph/docs, pull requests merged in 2024-05, with the labels that each got.

#287 Updated version of Cody Feature Parity Reference
  docs/cody/clients/feature-reference.mdx
Labels: documentation, enhancement

#290 Ship improvements to Cody clients index page
  docs/cody/clients/index.mdx
Labels: documentation, enhancement

#291 Add Ollama Support in Free
  docs/cody/clients/feature-reference.mdx
Labels: bug, documentation

#295 Fix ToC formatting in Beta features docs
  docs/admin/beta_and_experimental_features.mdx
Labels: bug, documentation

#298 Rmv faulty entry
  docs/code_insights/explanations/administration_and_security_of_code_insights.mdx
  docs/cody/clients/feature-reference.mdx
Labels: bug, documentation, enhancement

#299 Add 5.4 banner notices
  docs/code-search/queries/index.mdx
  docs/code-search/queries/language.mdx
Labels: documentation, enhancement

#307 Remove JSON file from Dev docs 5.2
  docs/versioned/5.2/dev/background-information/scim_postman_collection.json
Labels: bug, documentation

#318 Add Resource Estimator and AWS OneClick docs in version 5.2
  docs/versioned/5.2/admin/deploy/machine-images/aws-oneclick.mdx
  docs/versioned/5.2/admin/deploy/resource_estimator.mdx
Labels: documentation, enhancement

#322 Added version navigations
  src/components/Navigation.tsx
  src/components/PrevNextLinks.tsx
  src/data/navigation.ts
Labels: bug, documentation, enhancement

#323 Add docs for VS Code 1.18 release
  docs/cody/capabilities/supported-models.mdx
  docs/cody/clients/feature-reference.mdx
  docs/cody/clients/install-vscode.mdx
Labels: documentation, enhancement

#333 Fix GitHub Discussions link in Cody docs
  docs/cody/index.mdx
  docs/versioned/5.2/cody/index.mdx
  docs/versioned/5.3/cody/index.mdx
Labels: bug, documentation

#330 Added copy code feature for mdx code blocks
  contentlayer.config.ts
  package.json
  pnpm-lock.yaml
  src/components/CopyButton.tsx
  src/components/MdxComponents.tsx
  src/components/PreCodeBlock.tsx
Labels: documentation, enhancement

#366 Remove mentions of Helm from our Upgrading guide
  docs/admin/updates/index.mdx
Labels: bug, documentation

#369 Add a redirector script for routing old docs versions to subdomain
  next.config.js
Labels: documentation, enhancement

#371 Add `target= _blank` in Version Selector to make redirect work
  src/components/VersionSelector.tsx
Labels: documentation, enhancement

#372 Edit paths for versions
  next.config.js
  src/data/versions.ts
Labels: documentation, enhancement

#368 Add Sourcegraph Release Plan to docs
  docs/legacy.mdx
  docs/releases.mdx
  src/data/navigation.ts
Labels: documentation, enhancement

#376 Add new docs for UX changes in VS Code
  docs/cody/clients/install-vscode.mdx
  docs/cody/quickstart.mdx
Labels: documentation, enhancement
