Repository sourcegraph/docs, pull requests merged in 2024-01, with the labels that each got.

#22 Fix ToC in Code Search Features docs
  docs/code_search/explanations/features.mdx
  public/search.json
Labels: bug, documentation

#24 Add Usage and Pricing section in Cody nav
  public/search.json
  src/data/navigation.ts
Labels: documentation, enhancement

#26 Replace the deprecated Slack channel URL with the Discord link
  docs/dev/setup/quickstart.mdx
  public/search.json
Labels: bug, documentation

#29 🐛 FIX: Theme flicker
  .gitignore
  public/search.json
  src/app/layout.tsx
  src/app/providers.tsx
  src/components/ThemeSelector.tsx
  src/components/icons/CodeGraphIcon.tsx
  src/components/icons/CodeSearchIcon.tsx
  src/components/icons/CodebaseIcon.tsx
  src/components/icons/CodyIcon.tsx
  src/components/icons/PuginsIcon.tsx
  src/components/icons/SecurityIcon.tsx
  src/images/hero.svg
Labels: bug, documentation, enhancement

#38 Add missing content in Cloud docs
  docs/cloud/index.mdx
  docs/cloud/private_connectivity_aws.mdx
  docs/cloud/private_connectivity_gcp.mdx
  docs/cloud/private_connectivity_public_lb.mdx
  docs/cloud/private_connectivity_sourcegraph_connect.mdx
Labels: bug, documentation, enhancement

#41 Remove installation links and add warning callouts in Cody App docs
  docs/cody/clients/app/app_configuration.mdx
  docs/cody/clients/app/index.mdx
  docs/cody/clients/app/integrations.mdx
  docs/cody/clients/app/release-pipeline.mdx
  docs/cody/clients/app/troubleshooting.mdx
Labels: bug, documentation

#43 Update preview URLs details in README
  README.md
Labels: documentation, enhancement

#44 Fix docs in Admin Repo Permissions
  docs/admin/permissions/index.mdx
Labels: bug, documentation

#45 Add docs for Authenticating Cody with other VS Code forks
  docs/cody/clients/install-vscode.mdx
Labels: documentation, enhancement

#47 Replace Code AI platform with Code Intelligence platform
  docs/index.mdx
Labels: documentation, enhancement

#50 Add changleog page
  docs/CHANGELOG.mdx
  src/data/navigation.ts
Labels: documentation, enhancement

#63 Add Search Query Language Reference
  docs/code-search/queries/language.mdx
Labels: documentation, enhancement

#64 Improve formatting for Code Search Language docs
  docs/code-search/queries/language.mdx
Labels: documentation, enhancement

#65 Rename Code AI to Code Intelligence
  src/data/navigation.ts
Labels: bug, documentation

#66 Fix nav links
  src/data/navigation.ts
Labels: bug, documentation
