Repository sourcegraph/docs, pull requests merged in 2024-08, with the labels that each got.

#546 Docs for Prompts and Prompt Library
  docs/cody/capabilities/commands.mdx
  docs/cody/clients/cody-with-sourcegraph.mdx
  docs/cody/clients/feature-reference.mdx
  docs/cody/clients/install-vscode.mdx
  docs/cody/index.mdx
  docs/cody/quickstart.mdx
  src/data/navigation.ts
Labels: documentation, enhancement

#547 Docs for Saved Searches for the Aug release
  docs/code-search/working/saved_searches.mdx
Labels: documentation, enhancement

#537 Docs working branch for the August 7th release
  README.md
  docs.config.js
  docs/admin/repo/metadata.mdx
  docs/admin/repo/perforce.mdx
  docs/admin/search.mdx
  docs/code-search/queries/language.mdx
  docs/code-search/working/saved_searches.mdx
  docs/cody/capabilities/commands.mdx
  docs/cody/capabilities/ignore-context.mdx
  docs/cody/clients/cody-with-sourcegraph.mdx
  docs/cody/clients/feature-reference.mdx
  docs/cody/clients/install-vscode.mdx
  docs/cody/index.mdx
  docs/cody/quickstart.mdx
  docs/legacy.mdx
  next.config.js
  src/components/MdxComponents.tsx
  src/data/navigation.ts
  src/data/versions.ts
Labels: documentation, enhancement

#554 Remove old versions from version selector drop down
  docs/legacy.mdx
  src/data/versions.ts
Labels: documentation, enhancement

#556 Add docs about the new Code Search experience
  docs/code-search/features.mdx
Labels: documentation, enhancement

#564 Add more details about the new Search UI
  docs/code-search/features.mdx
Labels: documentation, enhancement

#570 📦 NEW: Working redirects
  next.config.js
Labels: bug, documentation, enhancement

#552 Docs for inline fix in JetBrains
  docs/cody/clients/install-jetbrains.mdx
Labels: documentation, enhancement

#579 Refactor our feature parity reference for Cody clients
  docs/cody/clients/feature-reference.mdx
Labels: documentation, enhancement

#586 Add Cody docs for VS Code v1.32 release
  docs/cody/capabilities/autocomplete.mdx
  docs/cody/capabilities/supported-models.mdx
  docs/cody/clients/install-vscode.mdx
Labels: documentation, enhancement

#595 Fix broken image in context retrieval
  docs/cody/clients/install-vscode.mdx
Labels: bug, documentation

#596 Add supported model configuration and llm matrix in docs
  docs/cody/clients/enable-cody-enterprise.mdx
Labels: bug, documentation

#597 Add EAP notice for model configuration
  docs/cody/clients/model-configuration.mdx
Labels: documentation, enhancement

#600 Merge feature parity table into one
  docs/cody/clients/feature-reference.mdx
Labels: documentation, enhancement

#601 Update feature-reference.mdx
  docs/cody/clients/feature-reference.mdx
Labels: bug, documentation

#602 Add links to Deployment docs in Releases
  docs/releases.mdx
Labels: bug, documentation, enhancement

#536 Fix broken Markdown links
  docs/admin/deploy/docker-compose/index.mdx
  docs/cody/usage-and-pricing.mdx
Labels: bug, documentation

#606 Docs changes for Cody featuring Sourcegraph v5.7 release
  docs/batch-changes/configuring-credentials.mdx
  docs/cody/clients/cody-with-sourcegraph.mdx
  docs/cody/clients/feature-reference.mdx
  docs/cody/clients/install-jetbrains.mdx
  docs/cody/clients/install-vscode.mdx
  docs/cody/usage-and-pricing.mdx
Labels: documentation, enhancement

#611 Update link in readme to add images/videos
  README.md
Labels: bug, documentation

#612 Updates adding media assets guidelines in readme
  README.md
Labels: documentation, enhancement
